# Encrypt disks with LUCK

- name: Pre requesites
  include: pre_requesites.yml

- name: Generate keys
  include: generate_keys.yml

- name: Create partitions
  include: partition.yml

- name: Encrypt disks
  include: encrypt.yml

