#
# Pre-Requesites
#

- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
  - cryptsetup
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
